# frozen_string_literal: true

Rails.application.configure do
  config.cache_classes = false
  config.eager_load = false
  config.consider_all_requests_local = true
  config.action_controller.perform_caching = false
  config.active_support.deprecation = :log

  # config/initializers/docs_pages.rb defines DocsPages::PAGES, which routes.rb, DocsController
  # and the docs layout's sidebar all read from -- but initializers only run once at boot, so a
  # page added to the registry has no route (and DocsController no action for it) until a
  # restart. Watch the file and, on change, redefine the constant and redraw routes so a new or
  # regrouped page works on the next request.
  #
  # Registering the checker on Rails.application.reloaders (rather than just calling it from a
  # to_prepare hook) is what makes an edit here also unload autoloaded constants like
  # DocsController: Rails only clears those when some reloader reports a change, and
  # DocsController's actions are themselves generated by looping over DocsPages::PAGES, so it
  # needs to reload too or it keeps its stale action list even after the registry is current.
  docs_pages_path = Rails.root.join('config/initializers/docs_pages.rb')
  docs_pages_checker = ActiveSupport::FileUpdateChecker.new([docs_pages_path.to_s]) do
    # remove_const before load (rather than require) so re-running the file doesn't warn about
    # an already-initialized constant.
    Object.send(:remove_const, :DocsPages) if Object.const_defined?(:DocsPages)
    load docs_pages_path
    Rails.application.reload_routes!
  end
  Rails.application.reloaders << docs_pages_checker
  config.to_prepare { docs_pages_checker.execute_if_updated }
end
